apiVersion: apps/v1
kind: Deployment
metadata:
  name: banco-digital
  labels:
    app: banco-digital
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banco-digital
  template:
    metadata:
      labels:
        app: banco-digital
    spec:
      containers:
      - name: banco-digital
        image: banco-digital:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BROKERS
          value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: banco-digital
spec:
  selector:
    app: banco-digital
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer 