apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: banco_digital
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: admin123
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banco-digital
  labels:
    app: banco-digital
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banco-digital
  template:
    metadata:
      labels:
        app: banco-digital
    spec:
      containers:
      - name: banco-digital
        image: banco-digital:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: DATABASE_URL
          value: "postgresql://admin:admin123@postgres:5432/banco_digital?sslmode=disable"
---
apiVersion: v1
kind: Service
metadata:
  name: banco-digital
spec:
  selector:
    app: banco-digital
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer